<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite errors="0" failures="0" hostname="acaz-PC" id="0" name="UserPersistenceIntegrationSpec" package="testingpractice" tests="2" time="0.302" timestamp="2016-03-17T14:26:25">
      <properties />

      <testcase classname="testingpractice.UserPersistenceIntegrationSpec" name="count grades for an specific user" time="0.279" />

      <testcase classname="testingpractice.UserPersistenceIntegrationSpec" name="get grades average for an specific user" time="0.022" />

      <system-out><![CDATA[--Output from count grades for an specific user--
--Output from get grades average for an specific user--
]]></system-out>

      <system-err><![CDATA[--Output from count grades for an specific user--
--Output from get grades average for an specific user--
]]></system-err>

  </testsuite>
  <testsuite errors="5" failures="1" hostname="acaz-PC" id="1" name="GradesControllerSpec" package="testingpractice" tests="7" time="7.708" timestamp="2016-03-17T14:26:04">
      <properties />

      <testcase classname="testingpractice.GradesControllerSpec" name="testing periods size" time="6.653">
          <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at java.lang.String.indexOf(String.java:1718)
	at java.lang.String.indexOf(String.java:1698)
	at testingpractice.GradesController$_closure6.doCall(GradesController.groovy:202)
	at testingpractice.GradesControllerSpec.testing periods size(GradesControllerSpec.groovy:40)
</error>

      </testcase>

      <testcase classname="testingpractice.GradesControllerSpec" name="testing periods name" time="0.048">
          <failure message="Condition not satisfied:&#xa;&#xa;periodNames[7].toString().trim().equals(&quot;2015-II&quot;)&#xa;|          |   |          |      |&#xa;[]         |   null       null   false&#xa;           null&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Condition not satisfied:

periodNames[7].toString().trim().equals(&quot;2015-II&quot;)
|          |   |          |      |
[]         |   null       null   false
           null

	at testingpractice.GradesControllerSpec.testing periods name(GradesControllerSpec.groovy:50)
</failure>

      </testcase>

      <testcase classname="testingpractice.GradesControllerSpec" name="getPeriods accepts null values" time="0.185" />

      <testcase classname="testingpractice.GradesControllerSpec" name="get subjects size" time="0.144">
          <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at java.lang.String.indexOf(String.java:1718)
	at java.lang.String.indexOf(String.java:1698)
	at testingpractice.GradesController$_closure6.doCall(GradesController.groovy:202)
	at testingpractice.GradesControllerSpec.get subjects size(GradesControllerSpec.groovy:62)
</error>

      </testcase>

      <testcase classname="testingpractice.GradesControllerSpec" name="get subjects PAPA" time="0.307">
          <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at java.lang.String.indexOf(String.java:1718)
	at java.lang.String.indexOf(String.java:1698)
	at testingpractice.GradesController$_closure6.doCall(GradesController.groovy:202)
	at testingpractice.GradesControllerSpec.get subjects PAPA(GradesControllerSpec.groovy:72)
</error>

          <error type="java.lang.NullPointerException">java.lang.NullPointerException
</error>

          <error type="java.lang.NullPointerException">java.lang.NullPointerException
</error>

          <error type="java.lang.NullPointerException">java.lang.NullPointerException
</error>

      </testcase>

      <testcase classname="testingpractice.GradesControllerSpec" name="get subjects PA" time="0.138">
          <error type="java.lang.NullPointerException">java.lang.NullPointerException
</error>

          <error type="java.lang.NullPointerException">java.lang.NullPointerException
</error>

          <error type="java.lang.NullPointerException">java.lang.NullPointerException
</error>

          <error type="java.lang.NullPointerException">java.lang.NullPointerException
</error>

      </testcase>

      <testcase classname="testingpractice.GradesControllerSpec" name="get progress" time="0.147">
          <error message="1" type="java.lang.ArrayIndexOutOfBoundsException">java.lang.ArrayIndexOutOfBoundsException: 1
	at testingpractice.GradesController.closure2$_closure14(GradesController.groovy:99)
	at testingpractice.GradesController$_closure2.doCall(GradesController.groovy:98)
	at testingpractice.GradesControllerSpec.get progress(GradesControllerSpec.groovy:101)
</error>

          <error message="1" type="java.lang.ArrayIndexOutOfBoundsException">java.lang.ArrayIndexOutOfBoundsException: 1
	at testingpractice.GradesController.closure2$_closure14(GradesController.groovy:99)
	at testingpractice.GradesController$_closure2.doCall(GradesController.groovy:98)
	at testingpractice.GradesControllerSpec.get progress(GradesControllerSpec.groovy:101)
</error>

          <error message="1" type="java.lang.ArrayIndexOutOfBoundsException">java.lang.ArrayIndexOutOfBoundsException: 1
	at testingpractice.GradesController.closure2$_closure14(GradesController.groovy:99)
	at testingpractice.GradesController$_closure2.doCall(GradesController.groovy:98)
	at testingpractice.GradesControllerSpec.get progress(GradesControllerSpec.groovy:101)
</error>

          <error message="1" type="java.lang.ArrayIndexOutOfBoundsException">java.lang.ArrayIndexOutOfBoundsException: 1
	at testingpractice.GradesController.closure2$_closure14(GradesController.groovy:99)
	at testingpractice.GradesController$_closure2.doCall(GradesController.groovy:98)
	at testingpractice.GradesControllerSpec.get progress(GradesControllerSpec.groovy:101)
</error>

          <error message="1" type="java.lang.ArrayIndexOutOfBoundsException">java.lang.ArrayIndexOutOfBoundsException: 1
	at testingpractice.GradesController.closure2$_closure14(GradesController.groovy:99)
	at testingpractice.GradesController$_closure2.doCall(GradesController.groovy:98)
	at testingpractice.GradesControllerSpec.get progress(GradesControllerSpec.groovy:101)
</error>

          <error message="1" type="java.lang.ArrayIndexOutOfBoundsException">java.lang.ArrayIndexOutOfBoundsException: 1
	at testingpractice.GradesController.closure2$_closure14(GradesController.groovy:99)
	at testingpractice.GradesController$_closure2.doCall(GradesController.groovy:98)
	at testingpractice.GradesControllerSpec.get progress(GradesControllerSpec.groovy:101)
</error>

          <error message="1" type="java.lang.ArrayIndexOutOfBoundsException">java.lang.ArrayIndexOutOfBoundsException: 1
	at testingpractice.GradesController.closure2$_closure14(GradesController.groovy:99)
	at testingpractice.GradesController$_closure2.doCall(GradesController.groovy:98)
	at testingpractice.GradesControllerSpec.get progress(GradesControllerSpec.groovy:101)
</error>

          <error message="1" type="java.lang.ArrayIndexOutOfBoundsException">java.lang.ArrayIndexOutOfBoundsException: 1
	at testingpractice.GradesController.closure2$_closure14(GradesController.groovy:99)
	at testingpractice.GradesController$_closure2.doCall(GradesController.groovy:98)
	at testingpractice.GradesControllerSpec.get progress(GradesControllerSpec.groovy:101)
</error>

      </testcase>

      <system-out><![CDATA[--Output from testing periods size--
--Output from testing periods name--
--Output from getPeriods accepts null values--
--Output from get subjects size--
--Output from get subjects PAPA--
--Output from get subjects PA--
--Output from get progress--
]]></system-out>

      <system-err><![CDATA[--Output from testing periods size--
--Output from testing periods name--
--Output from getPeriods accepts null values--
--Output from get subjects size--
--Output from get subjects PAPA--
--Output from get subjects PA--
--Output from get progress--
]]></system-err>

  </testsuite>
</testsuites>
